name: Run Google Search Console Verification

on:
  push:
    branches: [ main ]   # Run otomatis saat ada push
  workflow_dispatch:       # Tetap bisa manual nanti

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: echo "Test workflow jalan"
